name: webifycms

networks:
  webifycms-docker:
    driver: bridge

volumes:
  webifycms-db:
    driver: local

services:
  # PHP service
  app:
    container_name: ${APP_ID}-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    working_dir: /var/www/html
    networks:
      - webifycms-docker
  
  # Nginx service
  server:
    container_name: ${APP_ID}-nginx
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_PORT_SSL}:443"
    restart: unless-stopped
    networks:
      - webifycms-docker
  
  # MariaDB service
  db:
    container_name: ${APP_ID}-db
    image: mariadb:10
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - webifycms-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - webifycms-docker